baseurl = "https://breastcancer.netlify.com/"
languageCode = "en-us"
title = "Breast Cancer Risk Factors"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Age"
    url = "/age/"
    weight = 1
[[menu.main]]
    name = "Menopause"
    url = "/menopause/" 
    weight = 2
[[menu.main]]
    name = "Ethnicity"
    url = "/ethnicity/" 
    weight = 3
[[menu.main]]
    name = "Recommendations"
    url = "/recommendations/" 
    weight = 4

[params]
    description = "Multimedia research project for AMED3002: Interrogating Biomedical and Health Data"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

