---
title: "Age"
output: html_document
---

```{r setup, include = FALSE}
# include = FALSE: Neither code nor output shown
# echo = FALSE: Only output shown

# Suppress all output by default
knitr::opts_chunk$set(echo = FALSE)

# Load required packages
library(ggplot2)

# Theme setup
my.theme <- theme_classic() + theme(plot.background = element_rect(NULL), panel.grid = element_line(NULL))
```

```{r read.data}
# Read in txt file
bcsc <- read.delim("Data/bcsc/risk.txt", header = FALSE, sep = "")

# Assign names to variables in the BCSC header
names(bcsc) <- c("menopaus", "agegrp", "density", "race", "hispanic", "bmi", "agefirst", "nrelbc", "brstproc", "lastmamm", "surgmeno", "hrt", "invasive", "cancer", "training", "count")
```

```{r plot}
# Create subset of BCSC data with only positive diagnoses
cancer.bcsc <- subset(bcsc, cancer == "1")

# Give labels to the agegrp factor (categorical variable)
agegrp.factor <- factor(cancer.bcsc$agegrp, labels = c("35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84"))

# Axes labels
age.plot <- ggplot(cancer.bcsc, aes(x = agegrp.factor)) + labs(title = "Effect of Age on the Incidence of Breast Cancer", x = "Age (Years)", y = "Frequency of Breast Cancer")

# Plot type and theming
age.plot + geom_bar(fill = "pink", colour = "black") + my.theme
```

```{r testing, include = FALSE}
# To see output, set include = TRUE

# One-way ANOVA
anova <- aov(agegrp ~ cancer, data = bcsc)
summary(anova)
```

The barplot represents the frequency of this cancer among the different age groups. The histogram is a normal distribution with the greatest incidence of breast cancer occurring from 50-60 years old. This increase in morbidity corresponds to the increase in women entering menopause.